name: Image Auto Test

on:
  push:
    branches: [ "main", "feat/test-suite" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build ssh image
      run: OMS_MODE=b IMG_NAME=oms-ssh USE_SSH=yes ${{ github.workspace }}/run.sh
    
    - name: Run ssh image without port expose
      run: OMS_MODE=r IMG_NAME=oms-ssh USE_SSH=yes ${{ github.workspace }}/run.sh
    - name: Test container status
      run: docker ps | grep oms-ssh

    - name: Test whether oms-ssh is built and run currectly
      run: docker exec oms-ssh runuser -u runner -- sudo systemctl status ssh || true
    - name: Try to start ssh
      run: docker exec oms-ssh runuser -u runner -- sudo systemctl start ssh
    - name: Try to start ssh
      run: docker exec oms-ssh runuser -u runner -- sudo systemctl status ssh

    - name: Run ssh image with port expose
      run: OMS_MODE=r IMG_NAME=oms-ssh CONTAINER_NAME=oms-ssh-expose USE_SSH=yes SSH_PORT=22222 ${{ github.workspace }}/run.sh
    - name: Test container status
      run: docker ps | grep oms-ssh-expose | grep '0.0.0.0:22222->22/tcp'

      # Test vnc
    - name: Build vnc image
      run: OMS_MODE=br IMG_NAME=oms-vnc USE_VNC=yes ${{ github.workspace }}/run.sh
      
    - name: Test whether oms-vnc is built and run currectly
      run: docker exec oms-vnc runuser -u runner -- sudo systemctl status tigervnc@:1 || true
    - name: Try to start vnc
      run: docker exec oms-vnc runuser -u runner -- sudo systemctl start tigervnc@:1
    - name: Check vnc
      run: docker exec oms-vnc runuser -u runner -- sudo systemctl status tigervnc@:1

    - name: Run vnc image with port expose
      run: |
        OMS_MODE=r IMG_NAME=oms-vnc CONTAINER_NAME=oms-vnc-expose \
        USE_VNC=yes VNC_PORT=5999 ${{ github.workspace }}/run.sh

      # Test novnc
    - name: Build novnc image
      run: OMS_MODE=br IMG_NAME=oms-novnc USE_NO_VNC=yes ${{ github.workspace }}/run.sh
      
    - name: Test whether oms-novnc is built and run currectly
      run: docker exec oms-novnc runuser -u runner -- sudo systemctl status tigervnc@:1 || true
    - name: Try to start tigervnc@:1
      run: docker exec oms-novnc runuser -u runner -- sudo systemctl start tigervnc@:1
    - name: Check tigervnc@:1
      run: docker exec oms-novnc runuser -u runner -- sudo systemctl status tigervnc@:1
      
    - name: Test whether oms-novnc is built and run currectly
      run: docker exec oms-novnc runuser -u runner -- sudo systemctl status novnc || true
    - name: Try to start novnc
      run: docker exec oms-novnc runuser -u runner -- sudo systemctl start novnc
    - name: Check novnc
      run: docker exec oms-novnc runuser -u runner -- sudo systemctl status novnc

    - name: Run novnc image with port expose
      run: |
        OMS_MODE=r IMG_NAME=oms-novnc CONTAINER_NAME=oms-novnc-expose \
        USE_NO_VNC=yes NO_VNC_PORT=5999 ${{ github.workspace }}/run.sh
